//leads
export const ADD_LEAD = "ADD_LEAD";
export const DELETE_LEAD = "DELETE_LEAD";
export const GET_LEADS = "GET_LEADS";

//errors header
export const GET_ERRORS = "GET_ERRORS";
//messages header
export const CREATE_MESSAGE = "CREATE_MESSAGE";

//user
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

//record
export const ADD_RECORD_FAIL = "ADD_RECORD_FAIL";
export const GET_RECORDS = "GET_RECORDS";
export const ADD_RECORD = "ADD_RECORD";
export const RECORD_REMOVED_SUCCESSFULLY = "RECORD_REMOVED_SUCCESSFULLY";

//record details
export const ADD_SELECTED_RECORD_TO_STORE = "ADD_SELECTED_RECORD_TO_STORE";
export const GET_RECORD_DETAILS = "GET_RECORD_DETAILS";
export const GET_ALL_RECORD_DETAILS = 'GET_ALL_RECORD_DETAILS';
export const ADD_RECORD_DETAIL = "ADD_RECORD_DETAIL";
export const ADD_RECORD_DETAIL_FAIL = "ADD_RECORD_DETAIL_FAIL";

// record detail video management
export const RECORD_DETAIL_PLAY_SUCCESSFULLY =  "RECORD_DETAIL_PLAY_SUCCESSFULLY";
export const RECORD_DETAIL_STOP_SUCCESSFULLY =  "RECORD_DETAIL_STOP_SUCCESSFULLY";
export const RECORD_DETAIL_REMOVED_SUCCESSFULLY =  "RECORD_DETAIL_REMOVED_SUCCESSFULLY";

// file management
export const FILE_UPLOAD_SUCCESSFULLY = "FILE_UPLOAD_SUCCESSFULLY";

